version: '3.8'

services:
  db-me:
    image: postgres:15          
    container_name: my_postgres
    environment:
      POSTGRES_DB: ${POSTGRE_DB}   
      POSTGRES_USER: ${POSTGRES_USER}      
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"             
    volumes:
      - db_data:/var/lib/postgresql/data  

volumes:
  db_data:
